[package]
name = "ferrous_renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "23.0"
anyhow = "1.0"
thiserror = "1.0"
ferrous_core = { path = "../ferrous_core" }
winit = "0.30" # el renderer puede necesitar winit mÃ¡s adelante
ferrous_gui = { path = "../ferrous_gui" }
bytemuck = { version = "1.14", features = ["derive"] }
glam = { workspace = true }

[dev-dependencies]
pollster = "0.3"
image = "0.24"
